### ISSUE TITLE
Why are object names with ‘.’ or ‘/’ replaced by ‘_’?

### ISSUE THREAD

**Issue by debraysimon** [bitpool/edge-bacnet#24]
Hello, 
I've noticed that object names with ‘-’ or ‘_’ are replaced by ‘_’. Is this due to the bacnet standard? I would like to be able to name my objects with these characters. How can I do this? 
Best regards

**Comment by dblanchie** [comment]
Yes this is because of BACnet reserved characters especially using "." This can be interpreted as a property by some systems. In relation to "/" we remove this as it can affect the output topic structure.

If you want to change the point name you can right click and set or export the read list use your preferred editor, do bulk changes and re import back.
